# Generated by Django 4.1.7 on 2023-03-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='track',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='utrack',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
