# Generated by Django 4.1.7 on 2023-03-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_timestamp_user_track_user_utrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delete', 'Delete')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='track',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='client',
            name='utimestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='client',
            name='utrack',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delete', 'Delete')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='track',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='utimestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='utrack',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
